//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autos()
        {
            this.BitacoraDeSolicitud = new HashSet<BitacoraDeSolicitud>();
        }
    
        public int IdAuto { get; set; }
        public string Folio { get; set; }
        public int IdMarca { get; set; }
        public int IdModelo { get; set; }
        public string Color { get; set; }
        public int IdTipoTransmision { get; set; }
        public string DescripcionEstetica { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual TiposTransmision TiposTransmision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraDeSolicitud> BitacoraDeSolicitud { get; set; }
    }
}
