//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraDeSolicitud
    {
        public int IdBitacoraDeSolicitud { get; set; }
        public int IdSolicitudDeTransporte { get; set; }
        public int IdAuto { get; set; }
    
        public virtual Autos Autos { get; set; }
        public virtual SolicitudDeTransporte SolicitudDeTransporte { get; set; }
    }
}
