//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDeTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudDeTransporte()
        {
            this.BitacoraDeSolicitud = new HashSet<BitacoraDeSolicitud>();
        }
    
        public int IdSolicitudDeTransporte { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NumeroDeLote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraDeSolicitud> BitacoraDeSolicitud { get; set; }
    }
}
